# Generated by Django 2.2.5 on 2019-09-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=36)),
                ('Email', models.CharField(max_length=50)),
                ('Course', models.TextField(max_length=20)),
                ('Sem', models.TextField(max_length=10)),
                ('Subjects', models.TextField(max_length=100)),
                ('Query', models.TextField()),
            ],
        ),
    ]
